version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      spring:
        patterns:
          - "org.springframework*"
      testing:
        patterns:
          - "org.testcontainers*"
          - "org.junit*"
          - "org.assertj*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directories:
      - /
      - /docker/postgres
    schedule:
      interval: weekly
